### ISSUE TITLE
login fails - provide valid credentials

### ISSUE THREAD

**Issue by ajgerace** [f5devcentral/f5-cli#10] opened 2020-05-04 18:25 UTC
BIG-IP version 15.1.0.1 and f5-cli v0.9.2 login fails with please provide valid credentials. 
The same username and password can successfully authenticate into the BIG-IP webUI using chrome browser.

I've attempted to uninstall/re-install f5-cli with same result.
Changed password gives same result.

gerace@app01:~/ansible$ f5 login --authentication-provider bigip --host 192.168.0.49 --user admin --password test123
2020-05-04 14:02:39,190 - f5sdk.bigip.mgmt_client - DEBUG: Performing ready check using port 443
2020-05-04 14:02:39,190 - f5sdk.bigip.mgmt_client - DEBUG: Logging in using user + password
2020-05-04 14:02:39,191 - f5sdk.bigip.mgmt_client - DEBUG: Getting authentication token
2020-05-04 14:02:39,191 - f5sdk.utils.http_utils - DEBUG: Making HTTP request: POST /mgmt/shared/authn/login
2020-05-04 14:02:43,570 - f5sdk.utils.http_utils - DEBUG: HTTP response: 401 F5 Authorization Required
Error: Failed to login to BIG-IP, please provide valid credentials.

**Comment by ajgerace** [comment] 2020-05-04 18:35
gerace@app01:~/ansible$ f5 --version
f5, version 0.9.2

**Comment by shyawnkarim** [comment] 2020-05-13 20:48
I was not able to reproduce this issue. Are you still experiencing it?

**Comment by ajgerace** [comment] 2020-05-13 21:09
I've stood up another system and am able to use f5-cli there.  I haven't seen this issue with the new system. I think we can close it and if it happens again I can open another issue.

**Comment by shyawnkarim** [comment] 2020-05-13 22:21
Closing. Ok, sounds good.

**Closed by shyawnkarim** 2020-05-13 22:21 UTC
Labels: bug
